const supabaseURL = "https://djxkltpmvivptaqotpym.supabase.co";
const supabaseKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqeGtsdHBtdml2cHRhcW90cHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA3ODQzNTUsImV4cCI6MjAyNjM2MDM1NX0.Dp3n8-Jr0MK3tsM8lfGgzzmZBr0a0c8phbYLWIcnCuE";
